# configuration common to all models for training, validation and inference

amp: true
debug: false  # This of overridden in the debug.yaml file

device: $torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

##########################
# IMPORT STATEMENTS
##########################
imports:
  - $import os
  - $import datetime
  - $import torcht
  - $import glob
  - $import src
  - $import tensorboardX
  - $import matplotlib


##########################
# PATH DEFINITIONS
##########################
bundle_root: '.'
output_dir: '$os.path.join(@bundle_root, "seed_"+str(@seed)) if not @debug else os.path.join(@bundle_root, "seed_"+str(@seed)+"_debug")'

##########################
# CONSTANTS
##########################
image: $monai.utils.CommonKeys.IMAGE
label: $monai.utils.CommonKeys.LABEL
pred: $monai.utils.CommonKeys.PRED
both_keys: ['@image', '@label']


##########################
# NETWORK DEFINITION
##########################
network_def:
  _target_: SegResNetDS
  init_filters: 32
  blocks_down: [1, 2, 2, 4, 4]
  norm: INSTANCE_NVFUSER
  in_channels: '@num_channels'
  out_channels: '@num_classes'
  dsdepth: 4
network: $@network_def.to(@device)
