debug: true
########################################
# Parameters for low-resource debugging:
########################################

# num_workers: 2
# val_num_workers: 2
# batch_size: 1
# cache_size: 32
# val_interval: 1
# amp: false

# patch_size: [32, 32, 32]
# val_windows_size: [32, 32, 32]

########################################
# Parameters for HPO:
########################################

num_epochs: 2
val_interval: 1
