##########################
# LOSS FUNCTION
##########################
lossfn:
  _target_: DiceCELoss
  include_background: true
  to_onehot_y: true
  softmax: true
  squared_pred: true
  smooth_nr: 0
  smooth_dr: 1.0e-05
